---
driver: {name: dokken}
verifier: {name: inspec}
transport: {name: dokken}
provisioner: {name: dokken}

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      privileged: true
      pid_one_command: /bin/systemd

  - name: debian-9
    driver:
      image: dokken/debian-9
      privileged: true
      pid_one_command: /bin/systemd

  - name: fedora-27
    driver:
      image: dokken/fedora-27
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd

  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[chef-collectd]
